### PR TITLE
Add flag to enable/disable invulTicks

### PR DESCRIPTION
**Pull request by Diet-Cola**

### CODE REVIEW

**Comment by Maxopoly** [comment]
This will reintroduce multiple fixed bugs where vanilla sources of damage (fire, lava, cactus) will damage you on every tick. Also makes PvP akin to the Combo modes in pvp practice servers where you can hit your opponent as often as you want. Imo this is worse behavior than current, all of this is a structural issue in the custom hit handling. It needs per damage type invul cooldown instead of using a single global invul state

**Comment by Diet-Cola** [comment]
This check escapes the EntityDamageEvent before the custom invul ticks behaviour is implemented though, when testing it reverts all damage behaviour back to vanillas state. This settings allows you to customize if you want the feature enabled or not since removing it from the config introduces the stuff such as 1 tick fire damage

**Comment by Diet-Cola** [comment]
[Current behaviour with invulTicksEnabled set to true](https://imgur.com/JZ1ZIaS)  

[Default vanilla behaviour when invulTicksEnabled set to false](https://imgur.com/a/AZJanbL)

**Comment by wingzero54** [comment]
Max you're a good developer but you have the memory of a snail. We've talked about this multiple times. Finale's current invul system is totally broken, you yourself said we just need to turn it off. In vanilla, you get 10 ticks of invul from magma block damage, then can take outside damage, then 10 ticks magma block damage, repeat. In Finale, you get permanent invulnerability. I have mentioned this back in like August. If you stand on a magma block for example, Finale makes you 100% invulnerable until you get off the magma block. In vanilla, you alternate between invulnerable and vulnerable. That is not the case with Finale. If you set Finale to 1 tick invulnerability, what it is doing is calculating damage from the magma block every 1 tick back to back. You are still invulnerable, all you've done is change how often you get damage from the magma block. Finale's invul system is totally broken, it doesn't do anything except break vanilla even more. Diet said he tested and it reverts to vanilla functionality, which is an improvement from where we are now.

**Comment by Maxopoly** [comment]
I am fully aware of what we discussed and the current issues. I stand by my statement made above.

Merging and deploying upon your request.

**Pull request merged**
